{% set name = "pytorch_tabular" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5329057bb2698a15c120ef8e2979e332db0e6ab344eb84f2460e41b50c6d4c56

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install --no-deps --no-build-isolation -vv .
      noarch: python
    requirements:
      host:
        - python >=3.7
        - setuptools
        - pip
      run:
        - python >=3.7
        - einops >=0.6.0,<0.8.0
        - scikit-learn >=1.3.0
        - category_encoders >=2.6.0,<2.7.0
        - pytorch >=1.11.0
        - pytorch-lightning >=2.0.0,<2.2.0
        - pytorch-tabnet >=4.0
        - torchmetrics >=0.10.0,<1.3.0
        - tensorboard >2.2.0,!=2.5.0
        - omegaconf >=2.3.0
        - numpy >=1.20.0
        - pandas >=1.1.5
        - matplotlib-base >3.1
        - protobuf >=3.20.0,<4.26.0
        - pyyaml >=5.4,<6.1.0
        - rich >=11.0.0
        - ipywidgets

    test:
      imports:
        - pytorch_tabular
      commands:
        - pip check
      requires:
        - pip

  - name: pytorch-tabular
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - pytorch_tabular

about:
  home: https://github.com/manujosephv/pytorch_tabular
  summary: A standard framework for using Deep Learning for tabular data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manujosephv
    - cheginit
