{% set name = "pytorch_tabular" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 467f034121420d5a903cd937183d2181c8fc27ee4916725e38e99cf1bea69135

build:
  number: 1

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install --no-deps --no-build-isolation -vv .
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - einops >=0.6.0,<0.8.0
        - scikit-learn >=1.3.0
        - pytorch >=1.11.0
        - pytorch-lightning >=2.0.0,<2.5.0
        - pytorch-tabnet =4.1
        - torchmetrics >=0.10.0,<1.6.0
        - tensorboard >2.2.0,!=2.5.0
        - omegaconf >=2.3.0
        - numpy >=1.20.0,<2.0
        - pandas >=1.1.5
        - matplotlib-base >3.1
        - protobuf >=3.20.0,<5.29.0
        - pyyaml >=5.4,<6.1.0
        - rich >=11.0.0
        - ipywidgets

    test:
      imports:
        - pytorch_tabular
      commands:
        - pip check
      requires:
        - pip

  - name: pytorch-tabular
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - pytorch_tabular

about:
  home: https://github.com/manujosephv/pytorch_tabular
  summary: A standard framework for using Deep Learning for tabular data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manujosephv
    - cheginit
